spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC

jwt:
  secret: ${JWT_SECRET}


logging:
  level:
    org:
      springframework:
        security=DEBUG: